defaults: &defaults
  host: localhost
  port: 27017

development:
  <<: *defaults
  database: test

test:
  <<: *defaults
  database: test

# set these environment variables on your prod server
production:
   <<: *defaults
   database: test
   username: <%= ENV['MONGO_USERNAME'] %>
   password: <%= ENV['MONGO_PASSWORD'] %>
